# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde82126a4130e85e76d4a62c52c8ef9fdcf8c4868ef10a5bdff1e52661b2baf87ec1e0c2c1e37f087664f72f438cb2152d8ab03d7d84a12241618d0385c5d43

test:
  secret_key_base: 161d34fcf26450fe817fa8e997379a07746dfe6f3d85f15031256b0dd9c0c859f9154ca24c5bb29e1181d11d2dfd0f43d7d324ab04ec3322227ae98eaadadff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
